import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

// Files exempted from the file-size caps. NEW files do NOT get added here.
// If you're about to add an entry, split the file instead.
//
// Entries here are PERMANENT: runtime kernel files that legitimately grow
// with the system (CLI command surface, migration runner). Splitting them
// would fragment a single coherent responsibility for no benefit. Adding to
// this list is a deliberate design decision, not a TODO.
const SIZE_OVERRIDES = [
  // The CLI command surface and the DB migration runner. Both grow with the
  // system and have a single coherent responsibility.
  'apps/server/src/cli.ts',
  'apps/server/src/db/index.ts',
  // Agent route hosts inline FileViewerPanel/terminalPanel scaffolding.
  // Eligible for further split if it keeps growing, but stays flat for now.
  'apps/web/src/routes/_app/agent.$agentId.tsx',
]

// PERMANENT_EXCEPTIONS: code that stays flat by design. Framework conventions
// (TanStack/Expo Router file-based routes), runtime kernel (DB), single-file
// utilities (~100 lines or less, no public surface), app entry points.
// Promoting these to domains/ would mean a README for a thin wrapper, so the
// boundary benefit does not outweigh the overhead. The relaxed rules stay
// relaxed forever. Adding an entry here is a deliberate design decision, not
// a TODO.
const PERMANENT_EXCEPTIONS = [
  // Web: TanStack Router file-based routes. Route files legitimately export
  // both `Route` and a default component, and they're filesystem-routed by
  // the framework (so they cannot live inside a domain).
  'apps/web/src/routes/**',
  // Web: cross-cutting web-only hooks (embedded-context, server status,
  // updater). Documented in apps/web/CLAUDE.md as the intentional home for
  // hooks that aren't owned by a single feature domain.
  'apps/web/src/hooks/**',
  // Web: cross-cutting web-only lib helpers (theme, sounds, flags, platform).
  // Documented in apps/web/CLAUDE.md as the intentional home.
  'apps/web/src/lib/**',
  // Web: the React entry component. Single file, no public surface.
  'apps/web/src/App.tsx',
  // Server: runtime kernel. Per-domain pieces live in `domains/<x>/db.ts` and
  // `domains/<x>/ws.ts`. `src/db/` holds the migration runner plus schema
  // barrel; the WebSocket connection lifecycle and composed event union now
  // live in `src/domains/ws/` (a domain in its own right). Documented in
  // apps/server/CLAUDE.md.
  'apps/server/src/db/**',
  'apps/server/src/domains/ws/**',
  // Server: single-file utilities and entry points (under ~100 lines each).
  // Documented in apps/server/CLAUDE.md as "stays flat at src root".
  'apps/server/src/index.ts',
  'apps/server/src/cli.ts',
  'apps/server/src/auth.ts',
  'apps/server/src/audit.ts',
  'apps/server/src/config.ts',
  'apps/server/src/sandbox.ts',
  'apps/server/src/types.ts',
  'apps/server/src/updater.ts',
  'apps/server/src/system-routes.ts',
  // Mobile: Expo Router file-based routes. Same constraint as TanStack (the
  // framework owns the directory).
  'apps/mobile/app/**',
  // Mobile: cross-cutting mobile-only lib helpers (`prefs.ts`,
  // `setupMessage.ts`). Documented in apps/mobile/CLAUDE.md.
  'apps/mobile/lib/**',
  // Mobile: theme tokens (StyleSheet equivalent of CSS vars), app entry, and
  // Expo entry. Single-file, no public surface.
  'apps/mobile/theme.ts',
  'apps/mobile/App.tsx',
  'apps/mobile/index.ts',
]

// Forbidden Tailwind color scales — clash with the warm taupe palette.
const FORBIDDEN_COLOR_REGEX =
  '\\b(bg|text|border|ring|outline|divide|placeholder|caret|accent|fill|stroke|shadow|from|to|via)-(zinc|slate|gray)(?:-\\d+)?\\b'

export default defineConfig([
  globalIgnores([
    '**/dist/**',
    '**/build/**',
    '**/.next/**',
    '**/.expo/**',
    '**/node_modules/**',
    '**/coverage/**',
    'apps/marketing/**',
    'apps/desktop/src-tauri/target/**',
    'packages/tokens/dist/**',
    // Auto-generated by fumadocs / Next.js. Already in .gitignore.
    'apps/docs/.source/**',
    'apps/docs/next-env.d.ts',
  ]),

  // ---- Plugin registration ----
  // All plugins are registered ONCE here so later blocks can override rules
  // without redeclaring (which the flat config forbids).
  {
    files: ['**/*.{ts,tsx,js,mjs}'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
  },

  // ---- Base: every TS/TSX file in the monorepo ----
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // Hard caps. SIZE_OVERRIDES exempts existing offenders.
      'max-lines': [
        'error',
        { max: 400, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],

      // Banned imports.
      //
      // Domain boundary rule (replaces the old "import only from the domain
      // barrel" rule). Per-domain `index.ts` barrels no longer exist; the
      // public surface of a domain is the set of its top-level files. Cross-
      // domain consumers may import from any top-level file but NOT from
      // subfolders (`components/`, `hooks/`, `service/`, `screens/`,
      // `dialogs/`, `views/`, `routes/`, `job/`). Intra-domain code uses
      // relative paths, which these alias-based patterns do not match.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lucide-react',
              message:
                'Use @tabler/icons-react. lucide-react has the wrong visual weight for this design system.',
            },
          ],
          patterns: [
            {
              group: [
                '@/domains/*/components/**',
                '@/domains/*/hooks/**',
                '@/domains/*/service/**',
                '@/domains/*/screens/**',
                '@/domains/*/dialogs/**',
                '@/domains/*/views/**',
                '@/domains/*/routes/**',
                '@/domains/*/sections/**',
                '@/domains/*/extract/**',
                '@/domains/*/job/**',
                '@/domains/*/sub-domains/**',
              ],
              message:
                'Cross-domain imports must reference a top-level file in the target domain. Subfolders (components/, hooks/, service/, screens/, etc.) are domain-internal. Expose the symbol via a top-level file (e.g. `domains/<x>/<Name>.ts`).',
            },
          ],
        },
      ],

      // Banned Tailwind color scales, plus banned internal dynamic imports.
      //
      // Dynamic imports of internal modules (relative paths or `@/` alias) are
      // forbidden. They defeat type-driven refactors (a renamed/moved file
      // breaks only at runtime), they cannot be statically pattern-matched by
      // the cross-domain boundary rule above, and the bundle-splitting benefit
      // is irrelevant on the server. The legitimate uses of `await import`
      // remaining in the codebase are package-level: optional native modules
      // (Tauri APIs in the web app) and CLI-only deferred loads (`@clack/prompts`
      // in `apps/server/src/cli.ts`). Those are bare package specifiers, not
      // relative paths, and this rule lets them through.
      'no-restricted-syntax': [
        'error',
        {
          selector: `Literal[value=/${FORBIDDEN_COLOR_REGEX}/]`,
          message:
            'Use design-system tokens (bg-background, bg-card, text-foreground, border-border, etc.) instead of hardcoded zinc/slate/gray.',
        },
        {
          selector: `TemplateElement[value.raw=/${FORBIDDEN_COLOR_REGEX}/]`,
          message:
            'Use design-system tokens (bg-background, bg-card, text-foreground, border-border, etc.) instead of hardcoded zinc/slate/gray.',
        },
        {
          selector: `ImportExpression[source.type='Literal'][source.value=/^(\\.|@\\/)/]`,
          message:
            'Internal dynamic imports are forbidden. Use a static `import { ... } from "..."` at the top of the file. Dynamic import is reserved for optional package-level dependencies (e.g. Tauri APIs when running in a Tauri context, CLI-only `@clack/prompts`).',
        },
      ],

      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],

      // Allow underscore-prefixed names to mark "intentionally unused" without
      // triggering the rule. Matches the TS-eslint default convention used by
      // many other monorepos.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },

  // Tighter cap for .tsx files (lines), looser cap per-function because JSX
  // is naturally verbose. Both still force decomposition when components grow.
  {
    files: ['**/*.tsx'],
    rules: {
      'max-lines': [
        'error',
        { max: 300, skipBlankLines: true, skipComments: true },
      ],
      // JSX makes render functions naturally verbose. Looser per-function cap
      // for components; the 300-line file cap still forces sensible decomposition.
      'max-lines-per-function': [
        'error',
        { max: 150, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
    },
  },

  // React Hooks rules — web + mobile + desktop + UI
  {
    files: [
      'apps/web/**/*.{ts,tsx}',
      'apps/mobile/**/*.{ts,tsx}',
      'apps/desktop/**/*.{ts,tsx}',
      'packages/ui/**/*.{ts,tsx}',
      'packages/shared/**/*.{ts,tsx}',
    ],
    rules: reactHooks.configs.flat.recommended.rules,
  },

  // Direct `await api.x.y()` in client component code must go through the
  // `useHuxfluxQuery` / `useHuxfluxMutation` wrappers. Direct fetches in a
  // component or hook bypass TanStack Query and grow ad-hoc try/catch +
  // manual `queryClient.invalidateQueries(...)` boilerplate. Anything that
  // genuinely needs to fire-and-forget (clipboard, native bridge, optimistic
  // rollback flows) gets a `// fire-and-forget; intentional` comment and a
  // `// eslint-disable-next-line no-restricted-syntax` directive next to the
  // call site so the exemption is reviewable.
  //
  // The AST shape we match is `await api.<slice>.<method>(...)` — i.e. the
  // `await` operand is a CallExpression whose callee is a MemberExpression on
  // a MemberExpression on the `api` identifier. Server code (apps/server/**)
  // and the shared package itself are exempt because the rule's target is
  // the client-side TanStack Query consumer, not the api slice definitions.
  {
    files: ['apps/web/src/**/*.{ts,tsx}', 'apps/mobile/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'warn',
        // Preserve the existing color / dynamic-import bans by re-listing
        // them at warn level (the global block at error level still applies
        // for non-component code).
        {
          selector: `Literal[value=/${FORBIDDEN_COLOR_REGEX}/]`,
          message:
            'Use design-system tokens (bg-background, bg-card, text-foreground, border-border, etc.) instead of hardcoded zinc/slate/gray.',
        },
        {
          selector: `TemplateElement[value.raw=/${FORBIDDEN_COLOR_REGEX}/]`,
          message:
            'Use design-system tokens (bg-background, bg-card, text-foreground, border-border, etc.) instead of hardcoded zinc/slate/gray.',
        },
        {
          selector: `ImportExpression[source.type='Literal'][source.value=/^(\\.|@\\/)/]`,
          message:
            'Internal dynamic imports are forbidden. Use a static `import { ... } from "..."` at the top of the file. Dynamic import is reserved for optional package-level dependencies (e.g. Tauri APIs when running in a Tauri context, CLI-only `@clack/prompts`).',
        },
        {
          selector:
            "AwaitExpression > CallExpression[callee.type='MemberExpression'][callee.object.type='MemberExpression'][callee.object.object.name='api']",
          message:
            'Direct `await api.x.y()` in component/hook code must go through `useHuxfluxQuery` (reads) or `useHuxfluxMutation` (mutations). Documented fire-and-forget cases (clipboard, native bridges, optimistic rollback flows) silence the rule with `// eslint-disable-next-line no-restricted-syntax` plus a `// fire-and-forget; intentional` comment.',
        },
      ],
    },
  },

  // React Refresh — web only (Vite)
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
  // ---- Permanent-exception softening ----
  // Code that stays flat by design (framework routes, runtime kernel, single-
  // file utilities, app entries). See the PERMANENT_EXCEPTIONS comment at the
  // top of this file.
  {
    files: PERMANENT_EXCEPTIONS,
    rules: {
      'max-lines-per-function': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/set-state-in-render': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/component-hook-factories': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/globals': 'warn',
      'react-hooks/static-components': 'warn',
      'react-hooks/unsupported-syntax': 'warn',
      'react-hooks/gating': 'warn',
      'react-hooks/error-boundaries': 'warn',
      'react-hooks/incompatible-library': 'warn',
      'react-hooks/no-deriving-state-in-effects': 'warn',
      'react-hooks/syntax': 'warn',
      'no-restricted-imports': 'warn',
      'no-restricted-syntax': 'warn',
      'react-refresh/only-export-components': 'warn',
      'no-empty': 'warn',
      'no-control-regex': 'warn',
      'no-useless-escape': 'warn',
      'no-case-declarations': 'warn',
      'prefer-const': 'warn',
    },
  },

  // Routes legitimately export both `Route` and a component (TanStack Router
  // convention). Placed AFTER PERMANENT_EXCEPTIONS so the disable wins; the
  // PERMANENT_EXCEPTIONS block above includes `apps/web/src/routes/**` and
  // re-enables the rule at warn level otherwise.
  {
    files: ['apps/web/src/routes/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // Size-cap overrides for permanent-kernel + backlog files. See the
  // SIZE_OVERRIDES comment at the top of this file for the distinction.
  {
    files: SIZE_OVERRIDES,
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
    },
  },

  // The eslint config itself uses long literal arrays.
  {
    files: ['eslint.config.js'],
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
    },
  },

  // Scripts under scripts/ are operational utilities.
  {
    files: ['scripts/**/*.{js,mjs,ts}'],
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'no-console': 'off',
    },
  },

  // Test files: routinely larger than production files thanks to fixtures and
  // assertion blocks. Bump the cap to 600, drop the per-function cap, and let
  // tests use console.* freely while debugging fixtures.
  {
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      'apps/server/test/**/*.ts',
    ],
    rules: {
      'max-lines': ['error', { max: 600, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': 'off',
      'no-console': 'off',
    },
  },
])
