/**
 * Generates dist/tokens.css from the token definitions.
 * Run with: tsx src/build.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dark } from './tokens'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = __dirname  // write alongside source so it's committed

function camelToKebab(str: string): string {
  return str.replace(/([A-Z])/g, (c) => `-${c.toLowerCase()}`)
}

const vars = Object.entries(dark)
  .map(([key, value]) => `  --${camelToKebab(key)}: ${value};`)
  .join('\n')

const css = `/* Generated by @huxflux/tokens — do not edit manually */\n.dark {\n${vars}\n}\n`

writeFileSync(resolve(distDir, 'tokens.css'), css, 'utf8')

console.log('✓ src/tokens.css')
