import type { ColorTheme } from "../types"

export const minLight: ColorTheme = {
  id: "min-light",
  name: "Min",
  light: true,
  preview: ["#ffffff", "#f5f5f5", "#1a1a1a", "#999999"],
  vars: {
    "--background": "#ffffff",
    "--foreground": "#1a1a1a",
    "--card": "#f5f5f5",
    "--card-foreground": "#1a1a1a",
    "--popover": "#f5f5f5",
    "--popover-foreground": "#1a1a1a",
    "--primary": "#1a1a1a",
    "--primary-foreground": "#ffffff",
    "--secondary": "#eeeeee",
    "--secondary-foreground": "#1a1a1a",
    "--muted": "#eeeeee",
    "--muted-foreground": "#888888",
    "--accent": "#eeeeee",
    "--accent-foreground": "#1a1a1a",
    "--placeholder": "#aaaaaa",
    "--destructive": "#d32f2f",
    "--border": "rgba(0, 0, 0, 0.10)",
    "--input": "rgba(0, 0, 0, 0.06)",
    "--ring": "#888888",
    "--sidebar": "#f5f5f5",
    "--sidebar-foreground": "#1a1a1a",
    "--sidebar-primary": "#1a1a1a",
    "--sidebar-primary-foreground": "#ffffff",
    "--sidebar-accent": "#eeeeee",
    "--sidebar-accent-foreground": "#1a1a1a",
    "--sidebar-border": "rgba(0, 0, 0, 0.08)",
    "--sidebar-ring": "#888888",
  },
  terminal: {
    background: "#ffffff",
    foreground: "#1a1a1a",
    cursor: "#1a1a1a",
    selectionBackground: "#eeeeee",
    black: "#1a1a1a", red: "#d32f2f", green: "#388e3c", yellow: "#f9a825",
    blue: "#1565c0", magenta: "#7b1fa2", cyan: "#00838f", white: "#ffffff",
    brightBlack: "#888888", brightRed: "#e53935", brightGreen: "#43a047",
    brightYellow: "#fbc02d", brightBlue: "#1e88e5", brightMagenta: "#8e24aa",
    brightCyan: "#0097a7", brightWhite: "#ffffff",
  },
}
